global using DataAccessLayer.Repositories.Abstract;
global using DataAccessLayer.Repositories.Concrete;
global using Entities.Abstract;
global using Entities.Concrete;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Linq.Expressions;
global using System.Reflection;